### ISSUE TITLE
Why compiler errors occur？

### ISSUE THREAD

**Issue by Garenyan** [deeplearning4j/dl4j-quickstart#1]
![image](https://user-images.githubusercontent.com/25759992/54403477-1e4bb080-470b-11e9-8bf3-fc34ac597526.png)
why compiler errors occur when I copy the file to my project?

**Comment by AlexDBlack** [comment]
Given the error, the only explanation I can see is that you are using an old version of DL4J.
Please upgrade to 1.0.0-beta3.

If you have further issues, you can ask here: https://gitter.im/deeplearning4j/deeplearning4j
